# Generated by Django 5.1.6 on 2025-02-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('user_agent', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=50)),
                ('screen_width', models.IntegerField()),
                ('screen_height', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('security_level', models.CharField(max_length=20)),
                ('alert_type', models.CharField(max_length=50)),
                ('is_blocked', models.BooleanField(default=False)),

            ],
        ),
    ]
