services:

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    restart: always
    env_file:
    - ./.env
    ports:
    - "443:443"
    volumes:
    - vo_srv:/var/www/html
    depends_on:
      service:
        condition: service_healthy
        restart: true
    networks:
    - srv_network

  store-webapp:
    build:
      context: ./store-webapp
      dockerfile: ./Dockerfile
    container_name: store-webapp
    env_file:
      - ./.env
    networks:
      - srv_network
    healthcheck:
      test: ["CMD","curl","-fs", "http://localhost:3030/"] # TODO Cambiar el test de Healtcheck por uno personalizado
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 5s

  service:
    build:
      context: ./service
      dockerfile: ./Dockerfile
    container_name: service
    env_file:
      - ./.env
    volumes:
      - vo_srv:/var/www/html
    networks:
      - srv_network
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:9090/api/actions/health-check/"]
      interval: 30s
      retries: 3
      start_period: 5s
      timeout: 5s

volumes:
  vo_srv:
    name: service
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adherrer/data/service
  vo_db:
    name: psql
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adherrer/data/psql

networks:
  srv_network:
    name: srv_network
    driver: bridge
